build:
  image: node:10-alpine
  stage: build
  script:
    - npm ci
    - npm run postinstall
    - npx ng build -c production-th
    - npx ng build -c production-en
  artifacts:
    paths:
      - dist/
    expire_in: 24 hours
  cache:
    key: build
    paths:
      - $HOME/.npm/

deploy-web:
  stage: deploy
  image: sarunint/firebase-tools:latest
  only:
    refs:
      - master
  dependencies:
    - build
  script:
    - firebase deploy --only hosting --token "$FIREBASE_TOKEN"
    - firebase deploy --only functions --token "$FIREBASE_TOKEN"

deploy-functions:
  stage: deploy
  image: sarunint/firebase-tools:latest
  only:
    refs:
      - master
  script:
    - cd functions
    - npm ci
    - firebase deploy --only functions --token "$FIREBASE_TOKEN"

stages:
  - build
  - deploy
