deploy-functions:
  stage: deploy
  image: sarunint/firebase-tools:latest
  when: manual
  only:
    refs:
      - master
  script:
    - cd functions
    - npm ci
    - firebase deploy --only functions --token "$FIREBASE_TOKEN"

stages:
  - deploy
